currency = {
    'NPR₨', '¥', 'C$', '៛', '₤', 
    'MYRRM', 'CHF', 'UAH₴', 'KGSлв', 
    'Kč', 'TTDTT$', 'HUFFt', 'Z$', 
    'AZNман', 'VEFBs', 'FKP£', 
    'PENS/.', 'LBP£', '₫', 'SHP£', 
    'MKDден', 'YER﷼', 'ZARR', 
    'ILS₪', 'CNY¥', 'GTQQ', 'CZKKč', 
    'JPY¥', '¢', 'CLP$', 'RUBруб', 
    'RONlei', 'MT', 'XCD$', 'P', 
    'Дин.', 'BRLR$', 'Q', 'Lek', 
    '₩', 'NOKkr', 'TT$', 'ман', 
    'TRL₤', 'R', '£', 'BSD$', 
    'BOB$b', '₱', 'DOPRD$', '؋', 
    'ден', 'KPW₩', 'ANGƒ', 'p.', 
    'RSDДин.', 'KZTлв', 'NT$', 
    'JMDJ$', 'Bs', 'SOSS', 'COP$', 
    'R$', 'Ls', 'NGN₦', 'kn', 
    'IDRRp', 'BMD$', 'B/.', 
    'SAR﷼', 'Rp', 'KRW₩', 'Gs', 
    'IMP£', 'лв', '$U', 'UZSлв', 
    'CAD$', 'SGD$', 'SEKkr', 'HNLL', 
    'ISKkr', 'MUR₨', 'GHC¢', 'Lt', 
    '₴', 'EUR€', '€', 'BZ$', 'BND$', 
    'GGP£', 'MZNMT', 'PHP₱', 'MXN$', 
    'SVC$', 'TVD$', '₦', 'S', 'BWPP', 
    '₪', 'J$', 'AWGƒ', 'TWDNT$', 
    '$', 'GIP£', 'AFN؋', 'UYU$U', 
    'JEP£', 'MNT₮', 'FJD$', 'PYGGs', 
    '$b', 'GBP£', 'BGNлв', 'LTLLt', 
    'BYRp.', '₡', 'CRC₡', 'HKD$', 
    'kr', 'RD$', 'руб', 'VND₫', 
    'ALLLek', 'EGP£', 'HRKkn', 
    'NZD$', 'SYP£', 'NAD$', '﷼', 
    '₭', 'KM', 'PABB/.', 'S/.', 
    'KYD$', 'RM', 'NIOC$', 'PKR₨', 
    'ARS$', 'KHR៛', 'EEKkr', 'CUP₱', 
    'THB฿', 'L', 'LRD$', 'SRD$', 
    '฿', 'BZDBZ$', 'LAK₭', 'USD$', 
    'BBD$', 'SBD$', 'ZWDZ$', 'PLNzł', 
    'LKR₨', 'SCR₨', 'IRR﷼', 'QAR﷼', 
    '₨', 'OMR﷼', 'AUD$', 'zł', 'ƒ', 
    'GYD$', '₮', 'lei', 'CHFCHF', 
    'BAMKM', 'Ft', 'DKKkr', 'LVLLs'
}